apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seafile
resources:
  - namespace.yaml
  - sealed-secret.yaml # was secret.yaml
  - mariadb-init.yaml # <- new ConfigMap
  - pvc.yaml
  - mariadb.yaml
  - redis.yaml
  - seafile.yaml
  - ingress.yaml
