apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# Patch storage sizes / hostnames here per-environment if desired.
# patches:
#   - target:
#       kind: Ingress
#       name: seafile
#     patch: |-
#       - op: replace
#         path: /spec/rules/0/host
#         value: seafile.thedondon.org
