---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-argocd
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_ARGOCD_TOKEN: AgCkxd8wUgTbbrE+VZCK7FBRXT4A3a9u3D5uENYyyVIid4oxosSx3Z699K/Lykjl8wq54nJkfeHiYzC0tH2lQeCeYE58D4iLWwjrZJafc5GyFqD4fwtSkV+qBxC1Inw4X3IX0SL1wr+cZ4v43pDbij1FqlVqYnwWlLdynuKvhJtMzqV5ObSgqZdUssPi8PqVfPxMq/Sbg5F4/DP+mHH68PqYTFn7SBT5w5OeC4I7VMMwUTVCZ0fGivfRdZETkP/V74rLMUI+XhVRUkjrqEqlQ8YosPKwMup0vXpliMdJ3S+LyYlA9icsAtpYsKctdlTvFsgvRfMc1wBm5oT8JHwlev+Wz34ndAHyhqYaJJR7xq8dZwVAiLMB4F8dd//Csxu4Lne4XYCrKYfkEejAoqCaiomIZEVtFzQ1IiGrzTcyLKzv7U+5OlQJJxvz/f7YsSqCkiDR1V2K5ynhJQ7SdQEb28yswSKSfD2L/ssuKMrxR6JlKnBUAa+N2AChSVYG/8NBpP6Im31EQLn5sys2L8fIRcdQqEaNOJvh3ijCbaL5ecCWaMV4QViUYcosb+Ef3Bopk849sgJ9+75a7qpGieZy/w4n04daoFOs3IpAt3GRTaCr+JY7SbzKR00iluaJDvRLzFhNKhsqI+g3+DvjKrbWM1QjdDR+ipzrDFRBYMlpG2R5MsrUveNLgo//zpzKYje/Wo6oOxPwYv2QKWaExwS5xQpYl7QTSs5GA+W5ZnfxbrfDVT7yqemDI/fGJIJ07Uurr36bj1AzZFHi9kmxsRdlfXlc7ssUkyjig92yaO+T/6+absxXWFWFO+QTlapzjhMqxCxSyYdnefe8BYa+0PfZlF6bZpgJ644WhK6eVQhHHRhId3wfO7hEcqcOFklPLAPSIyPnFTlVAu7dQBjw9qcsXIc6uM/LhbLsdEI2G/s+8FYZUFXY93F/INevJYv1QlkPK/uCV4BhNpioRq5MFdoo6lFxB83ulcFPoL51qgfm6boq5liTU60NJNpJDjsZomHQF9Q=
  template:
    metadata:
      name: homepage-argocd
      namespace: homepage
