---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    HASS_TOKEN: AgDO7m/m3YAb5hJDffC/3rYpw2j+n1ePRlvXIgsHhq44nul0JH6trO6tOkf6Ii2ThX1+jWbA/6VoLt44hwdHdrAp4aUoLAp9L86rb8QryKsC8OxTcak0eWG4nfFH6GtAPRQdbZ38QjkNdE3yp7s9CQIlPPuhJFkJFslsA/SKwGngbLLLSY0Rv8UR8g0XMi0QKaOKK8eVgxmWTKpllUKHb9v1hzOVn45gZ0eZ8jAlTZL9UsVUCzH8SXei9TA7p64BDhqrdUE4+laJ1YhIHBoeAZCe9rqTIXjK0QfRVy7ev4UumVdpwzhclZWZyoocdZtWMtmu9JOz7eVbcaj+p39HLfthfidJXqybnEu9Lhhc0U1oenhJHM0TwjgtyjvQ5VWf1AW3B5onE5d96CZp+oGpxeu5LzM90zaxzH9iBy5vNjPZWsmFP2/fQg5cbhX70L1MmyoT01ThkUB7/ElnDBwAKy1k98mWutRcWIIac0ULY4rexNbYPxdGhpqZ66PM6wLy17kVsSXl22zy8GbdjWjSRZcLRoLSLAf+aLGPGG7H4Ro1p8TYXggbe8xEzx0tWn9pkZC5BRWA7r7ZRfpGyBnj3eFX5WJegmG5mx2OENWL0SfZhh5RwVpw9IsezJpEoPnBaDfJIfVtL9JKKQ+F9aqfoOa5ND1CwMIwfIWsqM853pc7qZ7LCeOysfMsscw8oqw7SE5qAtBAo4P9hg==
    IMMICH_KEY: AgDO47wUsOp3WFfDPLuhSKEPvXKi0AC8Xsuj32bfsZqy+VN//IcPRGA9Eju00cZrnloVxqgS1uBzZ6eYnVBb5DrnNE7qt7TtoeUjTT81vnwno0W731Q6ouyrlSme/9WDdHtMVWzMhgQF/+bWmLKM6cBN97Hsvcj1AMcQmUZagyA4zIdXuoKazQZJG/rOjlDGIl5rGwZOv9ZMBk1F98s8FH5s0u8bfbni4jotuOQ21T1Nq21i9KsTPqbhO5NDO5lSRPWMDbBQe3tnR3oACzzm/ZCn5az49c28suj4mNp1HKXWUOuyWF/CuTYWLM+8nuv1hch+RlWsniiUmsj9hkUxPdx4hqiMrk5f1Yj7prwY9g7xnGisxrPjnFXCZV6+RJh45IDxRVadF6m1uiCXy6iq7Lxl1gEu2dmxzBrMAWCiRgg5k5LNe5wMVpH+Q206cuV+ky+Tvk+23L8VR2qTGcwQnB1Jsf31EOEiZoV5o4BfZO8ypOpNmDyWBdw7gw43Eoj/4NlibABfaMQMJq/lu8F/2vVByVEGSGUvUe7Y0/3KQSnc2D7GNpG+qhkcUm9Vg2/5eqHor54urICfSZrc/7qWyr4OjvRIAHiXSwI5eRjVySKpX95HHOYjfyqeSBRyzAZHFfEr0ZTm5WvEHo5sbj6A5CoQW0jFfHNRtAunFUSQYiOVg7a5Kw8sxPoVGKwUvbs5B/sHhntF4ZkTRw==
  template:
    metadata:
      name: homepage-secrets
      namespace: homepage
