apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgANRjs3weTSPacJAjxFuKI6uNSGdP7ghZ0BYJ07CnCVSWCCVJEnM1dt7RcH0AW/SrOqN1/k05UxWWtWPA9yASbYFPGNet4P03YnXizRmlig8xurO+eWxI/DEIJ9tFPPtg+3u09UD1SgDzkt2Wi/aY4uX//joNrLUaEFkizAX3wC0PF7jqnAKWy+qlzbFmu4giFDAnN/1EefZkbjiG7qs/DIjM/+s77KfA95FiOv9TeOwzBJXScS9rXcimcAmkVinSwiI5X5w3qSrbAu2rzE3neTXxRp0qr2tHJ5M/W+EJO+MDc6xs9SX7ib5bpDcXtdxYNzO4Id2zp/yLwnjdg8F0t2zcpmKHhMqWckbRdOP2491I+GctDf57gCmOdggjkh0Sc00tApk8+WmksDxl5seavM1S1GyhY7t5PBFS43BL0FjGm9z9fpnzEx1WGEhZrATSy4eozBzThRHJ6peJQgIyQdoL+cVfry59RjJ5M2vzmzR8l2EmvDTOAcz9App+s22r7CJe8coVjihzE/iqO4mED+Bsjxa+j4+Hfo22FlMpZldKY8Rmi70DIvrqJ2IFYx2i7UnrRg6v5XS00gCIxdBFfc9Q2hOvKBjm8jvBqV6UyYJAH5D6fuhqGv68oYCQEuJX+5IvehL/MEsmknn5MouBBZOOu/3IpN+9Ibub8KJT5ON8YWNpgnh6ySNMd8yJwpDfufIhbkr28W4jaKKyjrVeFUqia2uw==
  template:
    metadata:
      creationTimestamp: null
      name: immich-secrets
      namespace: immich
---
