apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - ingress.yaml

configMapGenerator:
  - name: gitea-config
    files:
      - app.ini=app.ini
    behavior: replace
