---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-secrets
  namespace: wikijs
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBySb19xGvfULM8UqAJK0XoIoGEWHI1rM5/w11O/fxX9d87vf20edbXOahkZ2m48untazRotJPDct1+nFH7yriyxiJoHKGW0NfoHx96h/K3FGKEyr8WsR15aWPqP7nYAhKtPBOrgqHes2gQ4GccajAaA8TaJb3glNk97EJGyxwY8OJJf6f5PddZTPSZPcrb7lgWpeIXTsGxt3UEUOUEpYACebn8VY31CiSjAnHxRVdX2x8F6i947+FCJ0AJzBdNsXNaKTilU/ZzJn9hdgjEdG//xPkRK9itiVd4cyAmURuTKdIKtR6zveF2gmUwJhoecIGXk04+nqkSMGULC1A9gEpwZvM5yMgIip/TY4Hw58Tm1ZSvBvRKv1m93isJ2Oco1oUs1+UpKrOgL6o/wsG3Lo1jn0DvvgQGZeikX3ZegNNz/Fvc0IZVU9ZSxuRYPqHr0uZL842QrVJ3PaUCa30ucwnAKB7UnrqTSyGPzxPibEuAiS0BX7YEw4rpmfqsQc7FF2mC8lwJl6Xycz2RvZLY5vyRzqRZUgfwEgOdBBNm+KDdYm83Yb2infSxqru1mkQERW0VrrJJMEVKJ37wKz39MXmvvAirDaDN0sdqvkFMZAaHRulbsRlTzq9EIoynAFQ+sLbAf8Cc344tSVP5s/DiypHbLzLZiYq7b6OddEg2Obehm2A7c9e0/VCED3KTx27vfTBqmJkplIFocxn59HXxqi9lew==
    POSTGRES_USER: AgBIXv1EXUmMlVH/FLvS4bryrhOZqz/z9xR1hMLwc+5iKkIJ21OEYbu1YSgNiaIfqYvm3v3TaNv+uYjgsOXVysCCZ/HDqksx4m3xJPvTbGeRLp8Zaa91n2bLvxL93BpfU0Ng9SkvXyH7/FcegUR+iAor+ECeZCqnBnwfVsow4C3vCGhlvmZHNQbT50OXv4MbtfFOWvxgXGg7C1xJTOaVWErOSpa6RXOSqRmcyKo7hY6WcNLJhKw1K0K7t4ZdWfsyCF87/x398CBoXq0SHAltUg5pZkI7r0QTq+JRFu0ul7gFjserL/ZNFl4SJiFlc+zpwkRtW4W+l24E87Mdci1GNN4obevOKBdrNUsxiyO0mcq3FPtI+QcMtErqNQMXq267kiRlWG+FceghEODzc3czDuN7IaV3lVi2awyjEFjO2GqdPTT9SaCUHLrdvEgWxktthFYBiKfe+CGs1+pWmEHnjpcEHFnYO+VCfXQGs0t0zD637Mz+NyJ94hmDbR3TSMVQWPy58aUzsM9bM0dMKGnWFSqHwfkhh4E4TW2kZwz00qEG2OcW0tNua+aHxaMMHvPJl3EvVwYHJgiEFT0hw01Bpni8In+yw5oapBloO0h2Fk7M9Gw9RuFNOS75G8w3C1Vxq/WSWZ0aiXEFsYOp92ipqnMK9BntV+CwKqu/1IPVosvnUlvZHna9fOajjh4fSLjXh3VWC+lWWgA=
  template:
    metadata:
      name: wikijs-secrets
      namespace: wikijs
