title: syntaxandsymbols
favicon: /favicon.png
theme: dark
color: slate
headerStyle: clean
layout:
  Infrastructure:
    style: row
    columns: 3
  Media & Files:
    style: row
    columns: 3
  Home:
    style: row
    columns: 3
