---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAJkvt1iaPEkv771G068bwsi6milpbRum3kdaAHBKbd9JIN8bLLdREPFw4nSUHcBoUtdxMc/NwnAzgxEzQjM3glsRhbeGS2Mmqde5Noxu5kfYezl+nJjlk4/YanlQSctTQ14ZBJ/NwtJwYi0151yK9uuU7x3MDyorEKk0dAJe8Sb1iY9tz8P7um6CdcUWPRsKmup7+/VRsT6KduZceIo+yVX9PToLWHvHM0hA9PZtRGvWBwaboDd/xc24MnrzfX0EB+81EEAW/UtVwZ9Yv51mmqeNDDjwYdA0Pf77tHMHRTv+byYGE1ZV3gghJrfHWN+YpRGncEJoxrNz7hU82MgmofDuNrx9ckA5WxsOSLrkZS+9g6Wv+D1gUtmlV8J1dMbcaLmeg/bcftiWkE8S8xbKnAPeunTWcd5gDIqNOhOzPSxlGXH3vp/5btlHU97JFn2mmtWwHJuC9pvlrqv6aHVCWQh1Iy6ffblaSWHp8N1SPpLJDQuEnRvi39F+GDJkCx/E4bRsAS0pJeCJ6e/v4S1ng2nLKjoxC6/g7lJpPokzuPWf3DAlJeYqqYZj3EuJ239wWMIHhLVSztFM603bf+vGPafue8HctTRUYTw7V1ISFgzgIzm1vJLt/Jvz5kXi95eHeDe2/0osb6vK7EJxOqGoITZXQduJ2iszEQrwpaJfydJBgv+dUXBAgGVqMIZ65KuN70d6egS61AfuN99ImU0iAjVWDReaIpIHcZSdbdyhXrrUy6Ms1Aw7tlZgo9IXlUjxVBq8pk3iyC/MYmkr503As4
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
