---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-secret
  namespace: n8n
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBgU2YQY1zk4d07El2D5WQ27s8iE2Vfr1wNhkAeyMtoQX5kl31q329Es3NqGw9bp/sfeYBZlJmM8x9gQY2Y+4ajk0A0yleTfgADPtmi9rynxkFxon76o1jLGiU79XnnyV3NTuXBLXET55cGURA8rnz2a6OP7q5GjyKtP8UyzDogQNGZAwSF3/3Wm6XQiNyiQbD1r7B/vCmE8R45aY7fSWY6xOq6anHlmCjJ3oNZtTFOla0OVaXXbPMDKw/RzqN3BE9j3/1wLrreVMugcOj5gn8zbw3Ct60sPVJvUqQdvsBpQrKY7ONHS/cWoHz4zSb9ZAIlTa6lVRDExxha5YVMNBakbr/tksUJYO2710dWpEKNMCg9nXSOtS5XEl7CWQeh8ML7RwUKaM2ZU6TiJk4rLSXw6F0bL6g5PRSeVsfq5LF19/G6lFjr9LbSg7CT8IqiSHgDZrO4Enhs1Eys4zPxNiGCVePNxPFVw/BRojy9ZaT3rc0wRrjpCTwIBcbDWc1xDUXn4V5eNzlJSqlfQB8+OeqrVmirlrsPaU5WW8PYvl0ld5mCNEEk3Bl49gq5C6Ll0LuJuM1FuAaDHc4lhodLEHE4WTtgtpz9sDyL3p0Sq36tPwrwaDvP1kHNZTuANGhdDRQBdzY1kRhbkgpyZB+DaTAb1ktYfdKLiNQtPXqbgCa/y+EWydvhfHzQhPxLUZE2WIRzYUN9NXibg0M3KbJLg68p7923ppC4jrBFpsXWOa7BSOnVhyJgvg8rOZd6elwMJSc=
    POSTGRES_USER: AgCx9CBR+8g1ohaQ+0W9qura/dMs9RZ9sHRIWGeugkfu0RNlXuUz9cwAhu8P14zkBxAzPi94epLAdz/BxNLwM8bmmhB3QT8Zn7SwNGA4zo+fQ6V+MABBx4tQ07peUQWOhny/6broEgTb61wpZjjDiK9jMvf2UtJadQT1hcqGXFh7AbIO+SCBZmK7dsmKcHRndzeeSwaZwzLiG3iDpv23/rMdtkwH9tVYhDZB31+QTp8jwK7opLHd+RvN2UUGK5N1DeboTW1PlMVcvfT67SaT/kB29A+JA6jqM27jg06ZnZ/fNzhACbJh+3YHufysa0x41Anf7RHTUMppGoGwtArJa4cE7DrCtoKW9GaI0vBdW2J9gDE8vjiBzzPUh1PWUbO8Kk9fRNgPQrOgBzVsBBB9S2LiDfLpfXT8Uuoc85csOT5EZXFqprRT0iQydCb/2LAbx2CDT3c5fg61QEaaIHOxSY65wLSjvvdh/mK0qGPYvEn7eSmbhppQIbyr9QBpImLXveJukVkqjF7R6fwHC0zUox6v1c0gYGtpP/3eR0NMtrTJicfRBkfVWP4Mq4SDksM5p6rHa4BqgjjIb/zketNqcf5/l7wi+MZmOl0MJDM+I2pdPd72zFXOF6UEu95ned91RKLk3/T80fYw2AIjIzGFO5TupLesaHmQbWCjKe+hN44J3J4NBtJlT/NgfPrVZc+0x9uqOz4=
  template:
    metadata:
      name: n8n-postgres-secret
      namespace: n8n
