apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: argocd
spec:
  encryptedData:
    credentials.json: AgCDmClrSQbXk5i4BLtpyOZteTg8jiZGf23umvvwhEZd8uPQ61wsUzTNiTwlHWBTYnJePhWG7vgm6VyN95Mf3x4ebQJP+AY1AiC9O0vFH6dSRL7Ti4GVeENSOm2OsAts7hmfS+E7P7KgkBOdaw1nP/VD3ZltqsxrxmgbmRXIeeK1YXxiCx75Chsuf7sFFdRAGKVB36O+i9rF3fl7juM4VtZRKMBljkyGHTcEPCmdwb2Ygw+BGVYZDTdoUOirIa5utxsptXqiwJxVMF3lIlvt+lF/rixmQF1E9jCayFWyiiECs5j52o+PrQrYzjLkRNKmb45Shl21xMrtQfuIPYzYarfdcJ8kr5imq5RWaDERl+8YIFVa52NqONvjlL+QEWuzASTkQmGGbXENmJ0nz801THUp9RS4GYztOielRUOc7jqVCJmfqjRi0Yi2US4rg79lQE3Targ3loehzRf41UfpztMA4nOWoQL3H36A2TYSams9s56BpEy/IeW9eHdWZc+Vnb6hSfkBbD/5D2bR/03EKpbPFgR3WnSoM0+en7cPsSTYrV1iY1JaUlT4J1O8IzBoC8Xeqw1JFITudmmGh6v4GxAGz5dfYMePyc6pPzB0aNA3aWfyn1t5rg9OpiYCX7pbIpFDjFhsk9nAVE59SyM/SHvI6EgzhQihH61ku4en0B3SPAWtSEx79sfEvpDd1ZuMquQxDYAVgCG7KnRHpRkj7h1RltVdocyURTE2saxItVCusDXISmPDky67IKYqg7CwGzpgD5x85+I/12RCABv5dAV1fX1xtCz9vFOKD0FQiYz47M0Lxz4p5OxWEFkoo3MYW5apgRNDb8defv8ngvVsrLzmeXSrweY8yIbJ5UKhDxDpDBuM5yRAqwHkUJtR8HEUasAHkAcqj90Zv55NrD0/G2xlhpi77MyUMk43B0ZX4vZZ
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: argocd
    type: Opaque
---
