apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgANuVez0W8pEqX8uYYNHNNx/VuJmdqiXncvccsrhaChiQ+LfcXHNDZAkMuSCXY3pvQND9YGKTTswqSHJNbqsFlQIBVDUvBE11vk36P1Do2EkeCmt/D/l4W9fnGSr6DPLiXrBR++cczOOguPhclyNwNNEekbe3uXBU/QXGtuiCG4dgT3xoKSAYAEH3QP3Dc0LfID3E3Y7p4N4vkyYeQoQuFmuSTvGebAh729GVA7i3bhHnMouPeZFceN7PZVpSXLJxDtgvenWdu6lt2NegoRqQ9oP/V61FdVIpUDQ8nedi2MSjBNV9fSFdfNoaEDMv4s30OvSun0vuu6K61LH+aD4TSzxfcsbljL/5i3NZd3SM8s5rydAPh8v8ptq5PRhpXLL/2Ewu32oNdMYscYQK115f9ARTo3tkVqpIGISCkJpurkGUqhMsbQdOc2QAuTJlHr71ozkSn4Iee/9wT5iM2QJD8bQOEJWdFgyDR4dQP+0q9bsNmSzPaxNbd9D1HALD3dnrwgZk+Cqd1fsEcTMlo6EEDyEud4whoDSoiHgHbD1z3gUOUH0gwG6UyoB3URggRvkVGFh1uxRU0eDoVQB+1XEscMyenwU4N3bQaQsXPRmh+tL384DnZ8PuzKoiju8B0n9KvdemkZ9wtx6Kz7qeBzkRSQZHg+uQS/VM3WVMbGdQCTCuR7uA2OLPxntpHhIRcB/b3rJgKCbcFms95v+UoHXxRX/0VTuVMBXTyYY4FTGfSEOwg/QjXPBMPJNlJ4oQKedW/TJJ1l3BOPhs9r7YyhvrD+QabdlSznOl2EHWL/9WDv5BVuHN+ARJUG3HuQeJPRXktLxJBa0aoe7Wx1+J1ORIyU35/K8S/FUDT67bJKqm/Q9uhYcSdgHk6uJG0dcRk9CE/Izb6f+x/Fr6sq8ikQNpBKveqXjgrpGlIJXfJo9Ka0
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
---
